def get_info(price_per_unit):
    info = {
        "customer": {
            "id": "a7df7848-c20f-4513-9a5d-f1b1916717be",
            "type": 1,
            "regNumber": "100277704",
            "supplierRegNumber": None,
            "name": "ТУ РОСИМУЩЕСТВА В КАМЧАТСКОМ КРАЕ",
            "fullName": "ТЕРРИТОРИАЛЬНОЕ УПРАВЛЕНИЕ ФЕДЕРАЛЬНОГО АГЕНТСТВА ПО УПРАВЛЕНИЮ ГОСУДАРСТВЕННЫМ ИМУЩЕСТВОМ В КАМЧАТСКОМ КРАЕ",
            "inn": "4101133149",
            "kpp": "410101001",
            "largestTaxpayerKpp": None,
            "ogrn": "1094101004865",
            "okved": "84.11.12",
            "okato": None,
            "okpo": None,
            "address": None,
            "postAddress": None,
            "regDate": "2018-10-30T08:35:30",
            "supplierRegDate": None,
            "isSMP": False,
            "isCustomer": True,
            "isSupplier": False,
            "subordinateLevel": 1,
            "subordinateLevelDescription": "Федеральный",
            "isDishonest44FzSupplierResponse": False,
            "isDishonest223FzSupplierResponse": False,
            "isSono": False,
            "isSelfEmployed": False,
            "director": "Куркина Евгения Сергеевна",
            "email": "tu41@rosim.ru",
            "phoneNumber": "7(415)242-02-47",
            "faxNumber": None,
            "webSiteUrl": "tu41.rosim.ru",
            "contactFio": None,
            "contactEmail": "tu41@rosim.ru",
            "contactPhone": "7(415)242-02-47",
            "bankInfo": {
                "bankName": None,
                "bankAddress": None,
                "bankBik": None,
                "bankCorrespondentAccount": None,
                "paymentAccount": None
            },
            "isPrivacyAgreementSignedByOrganization": False,
            "achievements": []
        },
        "supplier": {
            "id": "3463efcf-f7fa-4640-816a-4b3cc4306fbf",
            "type": 1,
            "regNumber": None,
            "supplierRegNumber": "300993913",
            "name": "ООО \"ТРАНСТЕХ\"",
            "fullName": "ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ \"ТРАНСПОРТНЫЕ ТЕХНОЛОГИИ\"",
            "inn": "6163232224",
            "kpp": "616301001",
            "largestTaxpayerKpp": None,
            "ogrn": "1246100008758",
            "okved": None,
            "okato": None,
            "okpo": None,
            "address": "344022, РОСТОВСКАЯ ОБЛАСТЬ, ул УЛ ОЧАКОВСКАЯ, д. Д. 39, кв. ПОМЕЩ. 13",
            "postAddress": "Ростовская обл, г Ростов-на-Дону, ул Очаковская, д 39, офис 13",
            "regDate": None,
            "supplierRegDate": "2024-10-25T12:32:23.780324",
            "isSMP": True,
            "isCustomer": False,
            "isSupplier": True,
            "subordinateLevel": 0,
            "subordinateLevelDescription": "Иной",
            "isDishonest44FzSupplierResponse": False,
            "isDishonest223FzSupplierResponse": False,
            "isSono": False,
            "isSelfEmployed": False,
            "director": None,
            "email": "sperik_ice@mail.ru",
            "phoneNumber": "+7(989)621-05-03",
            "faxNumber": None,
            "webSiteUrl": None,
            "contactFio": "Кузнецова  Ксения Геннадиевна",
            "contactEmail": "sperik_ice@mail.ru",
            "contactPhone": "+7(989)621-05-03",
            "bankInfo": {
                "bankName": "ФИЛИАЛ \"РОСТОВСКИЙ\" АО \"АЛЬФА-БАНК\"",
                "bankAddress": "344000, Ростовская обл, г Ростов-на-Дону, ул Красноармейская, д 206",
                "bankBik": "046015207",
                "bankCorrespondentAccount": "30101810500000000207",
                "paymentAccount": "40702810726270001080"
            },
            "isPrivacyAgreementSignedByOrganization": False,
            "achievements": []
        },
        "info": {
            "createdOn": "2024-11-27T07:39:43.674842",
            "tradeLotId": "fdfd5ec3-902f-4b3f-b54e-53046e738215",
            "id": "e8cb7d2f-fbd5-4993-bbe8-f3e98a2cd129",
            "applicationState": 1,
            "contactPerson": "Кузнецова  Ксения Геннадиевна",
            "contactData": "тел. +7(989)621-05-03, sperik_ice@mail.ru",
            "isAgreeToSupply": True,
            "decreasePercent": None,
            "unitPriceSum": price_per_unit,
            "unitPriceSumWithoutTax": price_per_unit,
            "calculatedTax": 0,
            "price": 137500,
            "priceWithoutTax": 128504.67,
            "deliveryPrice": 0,
            "totalPrice": 137500,
            "totalPriceWithoutTax": 128504.67,
            "documents": [
                {
                    "id": "a87c577c-97bf-4735-82ba-e890663c5d0e",
                    "createdOn": "2024-11-27T07:46:30.83236",
                    "name": "Заявки Транстех Березка.zip",
                    "documentName": None,
                    "typeName": None,
                    "size": None,
                    "type": 0,
                    "signatureId": None
                }
            ],
            "items": [
                {
                    "quotation": 5500,
                    "name": "ПРОВЕДЕНИЕ ЭКСПЕРТИЗЫ КАЧЕСТВА",
                    "description": "ПРОВЕДЕНИЕ ЭКСПЕРТИЗЫ ТЕХНИЧЕСКОГО СОСТОЯНИЯ",
                    "tradeLotItemOrder": 0,
                    "taxPercent": 7,
                    "countryOfOrigin": {
                        "name": "Россия",
                        "code": "643"
                    },
                    "offerId": "00000000-0000-0000-0000-000000000000",
                    "offerNumber": None,
                    "esklpCode": None,
                    "esklpName": None,
                    "isPriceWithTax": True,
                    "calculatedTax": 8995.33,
                    "sum": 137500,
                    "offerName": None,
                    "offerDescription": None,
                    "russianItemsRegistry": None,
                    "russianItemsRegistryNum": None,
                    "isReference": False,
                    "referenceOfferId": None,
                    "referenceOfferNumber": None,
                    "quantity": 25
                }
            ],
            "bankName": "ФИЛИАЛ \"РОСТОВСКИЙ\" АО \"АЛЬФА-БАНК\"",
            "bankAddress": "344000, Ростовская обл, г Ростов-на-Дону, ул Красноармейская, д 206",
            "correspondentAccount": "30101810500000000207",
            "paymentAccount": "40702810726270001080",
            "bik": "046015207",
            "applicationSubType": 0,
            "sessionConclusionContractPrice": None,
            "applicationImportDataRequests": [],
            "applicationPriceHidden": False
        },
        "trade": {
            "publishDate": "2024-11-27T03:38:18.881485",
            "number": "100277704124100004",
            "applicationGuarantee": 6875,
            "modificationNumber": 1,
            "lotUnitPriceSum": 137500,
            "isApplicationFillingProlongationHappened": False,
            "id": "82dc3eb5-5db6-42b5-866c-1045925a027a",
            "purchaseMethod": 4,
            "processingPurchaseMethod": None,
            "type": 1,
            "purchaseTypeTitle": "Закупка до 600 000 руб. (п. 4 ч.1 ст. 93 Закона №44-ФЗ)",
            "purchaseTypeId": "1",
            "contactFio": "Бондаренко ",
            "contactEmail": "tu41@rosim.gov.ru",
            "contactPhone": "7(415)242-55-85",
            "contactFax": None,
            "contactAddInfo": "",
            "stateDefenseOrder": False,
            "applicationFillingPeriod": 24,
            "isPlannedPurchase": False,
            "applicationFillingStartDate": None,
            "applicationFillingProlongationPeriod": None,
            "allowDocumentChanges": True,
            "isSmp": False,
            "isManuallyPublishApplicationReviewProtocol": True,
            "planRegistrationNumber": "",
            "lot": {
                "lotItems": [
                    {
                        "id": "00000000-0000-0000-0000-000000000000",
                        "orderNumber": 0,
                        "name": "ПРОВЕДЕНИЕ ЭКСПЕРТИЗЫ КАЧЕСТВА",
                        "quantity": 25,
                        "unitPrice": 5500,
                        "sum": 137500,
                        "quantityUndefined": False,
                        "okpd2": {
                            "code": "71.20.19.190",
                            "title": "Услуги по техническим испытаниям и анализу прочие, не включенные в другие группировки"
                        },
                        "esklp": None,
                        "ktru": {
                            "code": None,
                            "title": None
                        },
                        "eat": {
                            "code": "28420601",
                            "title": "ПРОВЕДЕНИЕ ЭКСПЕРТИЗЫ КАЧЕСТВА"
                        },
                        "okei": {
                            "code": "L796",
                            "title": "шт",
                            "precision": 0
                        },
                        "requireOfferSpecification": False,
                        "offerId": None,
                        "offerNumber": None,
                        "description": "ПРОВЕДЕНИЕ ЭКСПЕРТИЗЫ ТЕХНИЧЕСКОГО СОСТОЯНИЯ",
                        "countryOfOrigin": {
                            "name": "Россия",
                            "code": "643"
                        },
                        "priceOption": 1,
                        "priceOptionReason": None,
                        "russianItemsRegistry": None,
                        "russianItemsRegistryNum": None,
                        "ntin": None,
                        "isReference": False,
                        "isCreatedFromExternalCart": False,
                        "externalCartStoreUrl": None,
                        "referenceOfferId": None,
                        "referenceOfferNumber": None,
                        "ektruPassportNumber": None
                    }
                ],
                "description": None,
                "subject": " оказание услуг по экспертизе конфискованного, движимого бесхозяйного и иного имущества, обращенного в собственность государства, на предмет соответствия (несоответствия) объектов имущества требованиям о безопасности для жизни и здоровья человека, возможности (невозможности) их использования по обычному предназначению\n",
                "price": 137500,
                "isPriceEditedManually": False,
                "contractSignDate": "2024-12-03T00:00:00",
                "contractExpirationDate": "2025-11-30T00:00:00",
                "paymentTypes": [
                    2
                ],
                "paymentType": 2,
                "paymentCondition": 2,
                "paymentFrequency": None,
                "prepaidAmount": None,
                "paymentPrepayDetails": None,
                "dealTerminationInfo": "       Расторжение Контракта допускается по соглашению сторон, по решению суда, в случае одностороннего отказа стороны Контракта от исполнения Контракта в соответствии с гражданским законодательством. \nЗаказчик вправе принять решение об одностороннем отказе от исполнения Контракта по основаниям, порядку, предусмотренным Гражданским кодексом Российской Федерации для одностороннего отказа от исполнения отдельных видов обязательств. Кроме того, основаниями для расторжения настоящего Контракта в одностороннем порядке являются:\nесли отступления результата услуг от условий настоящего Контракта или иные недостатки результата услуг в установленный срок не были устранены Исполнителем либо являются существенными и неустранимыми;\nесли Исполнитель нарушил сроки оказания услуг (сроки начала и (или) окончания услуг и (или) промежуточные сроки оказания услуг) либо если во время оказания услуг стало очевидным, что они не будут осуществлены в срок.\n\n",
                "isDealTerminationAvailable": False,
                "additionalConditions": None,
                "ikz": "241410113314941010100100160000000244",
                "isTrusteeCustomer": None,
                "deliveryInfos": [
                    {
                        "deliveryScheduleInfo": None,
                        "deliveryInfo": "Территория Камчатского края. Заказчику не может быть заранее известно место нахождения объекта экспертизы, в связи, с чем необходимые для проведения экспертизы действия могут осуществляться на всей территории Камчатского края.\nРаботы выполняются по месту нахождения объектов с доставкой результата по адресу Заказчика",
                        "deliveryAddress": {
                            "formattedFullInfo": "г Петропавловск-Камчатский, ул Красинцев, д 19",
                            "okato": "30401000000",
                            "country": "Россия",
                            "countryCode": "RU",
                            "regionName": "Камчатский край",
                            "regionCode": "41",
                            "federalDistrict": None,
                            "area": None,
                            "city": "г Петропавловск-Камчатский",
                            "cityDistrict": None,
                            "settlement": None,
                            "street": "ул Красинцев",
                            "house": "д 19",
                            "office": None,
                            "planningStructure": "",
                            "additionalTerritory": "",
                            "landPlot": "",
                            "subordinateObject": "",
                            "postIndex": "683001",
                            "fiasCode": "42f1fa4c-5d30-474e-ac13-5c1bea236e35"
                        }
                    }
                ],
                "deliveryType": 1,
                "deliveryDate": "2024-12-15T00:00:00",
                "isDeliveryDateInDays": False,
                "deliveryPeriod": None,
                "isDeliveryDaysWorking": False,
                "documents": [
                    {
                        "id": "878f7d7e-09d1-4f2d-b805-3e20f7da0979",
                        "createdOn": "2024-11-27T00:38:13.29663",
                        "name": "Ответ Камчатский центр Экспертиз от 17.10.2024.pdf",
                        "documentName": None,
                        "typeName": None,
                        "size": 82999,
                        "type": 14,
                        "signatureId": "f31cf6ca-7b3e-4f8b-aa5a-b8d051d38ba9"
                    },
                    {
                        "id": "5b442978-25c2-4023-a4e4-8bf55e5107ed",
                        "createdOn": "2024-11-27T03:37:57.426724",
                        "name": "Проект ГК    ЭКСПЕРТИЗА.docx",
                        "documentName": None,
                        "typeName": None,
                        "size": 59192,
                        "type": 15,
                        "signatureId": "16481ad4-1e96-48dc-852d-f097d9b86f9b"
                    },
                    {
                        "id": "a406ca87-02da-4599-a2ce-0b19168b27a9",
                        "createdOn": "2024-11-27T03:37:58.138267",
                        "name": "Информация по закупке №100277704124100004_44.html",
                        "documentName": None,
                        "typeName": None,
                        "size": 0,
                        "type": 2,
                        "signatureId": "d15f71f6-9740-4a8a-9762-4acd3307239c"
                    },
                    {
                        "id": "5e19782f-4a85-496a-a804-f0532a44cdd8",
                        "createdOn": "2024-11-27T03:37:58.138267",
                        "name": "TradeDto-82dc3eb5-5db6-42b5-866c-1045925a027a.xml",
                        "documentName": None,
                        "typeName": None,
                        "size": 2860,
                        "type": 3,
                        "signatureId": "c55e0ae7-75e5-47c0-8799-93f0b41a616d"
                    }
                ],
                "contractType": 3,
                "isPaymentInDaysSinceDealExecuting": False,
                "isPaymentInDaysSinceSigninAcceptanceDocument": False,
                "paymentDateInDays": None,
                "isPaymentPeriodWorkDays": False,
                "paymentDate": None,
                "stateOrderId": None,
                "specAccountBank": None,
                "specAccountBik": None,
                "specAccountCorrespondingAccount": None,
                "specAccount": None,
                "priceSource": 1,
                "priceSourceOrganizationId": None,
                "priceSourceOrganizationType": 1,
                "priceSourceOrganizationInn": "4100041086",
                "priceSourceOrganizationKpp": "410001001",
                "priceSourceOrganizationName": "ООО \"КАМЧАТСКИЙ ЦЕНТР ЭКСПЕРТИЗ\"",
                "priceCalculationMethod": None,
                "priceSourceDocumentsUploadRefused": False,
                "isPriceSourceHidden": False,
                "needProposalDocumentation": False,
                "proposalDocumentationRequirements": None,
                "subType": 0,
                "responsibilities": [
                    {
                        "number": 1,
                        "description": "За неисполнение или ненадлежащее исполнение своих обязательств по настоящему Контракту Стороны несут ответственность в соответствии с действующим законодательством Российской Федерации.\n"
                    }
                ],
                "isRussianItemsPurchase": False,
                "paymentAccount": "40102810945370000031",
                "bankName": "УФК по Камчатскому краю",
                "bankCorrespondentAccount": "03211643000000013800",
                "bankBik": "013002402",
                "bankAddress": "683003, Камчатский край, г Петропавловск-Камчатский, ул Ленинградская, д 89",
                "additionalRequisitesAndInfo": None,
                "fkAccountNumber": "03381А23450",
                "correspondentFkAccountNumber": "40102810945370000031",
                "oktmo": "307010000",
                "kbk": "16701133941292150244",
                "useEmployeeBankRequisites": False,
                "isFillingApplicationByPart1Particle31Law44": True,
                "budget": "Федеральный бюджет",
                "isNoNdsWinner": False,
                "isFsk": False,
                "isRostechRequirementsConfirmation": False,
                "isUseOf11DecimalPlacesInUnitPrice": False,
                "tradeLotImportDataRequests": None,
                "customerAcceptanceServiceDeadlineInfo": "Заказчик вправе проводить приемку результата услуг в течение в течении 5 (пяти) рабочих дней",
                "supplierFulfillmentDocumentsProvisionInfo": "Вместе с результатами услуг Исполнитель обязан не позднее 10 числа месяца, следующего за отчетным, предоставить документы, подтверждающие факт передачи результата оказанных услуг - акт приемки - сдачи оказанных услуг (2-а экземпляра) (согласно приложению 3 к договору), и документы для оплаты услуг - счет; счёт –фактуру (при наличии).\n"
            },
            "is44FzRnp": False,
            "is223FzRnp": False,
            "isCustomerRnp": False,
            "isPhysicalPersonParticipationProhibited": False,
            "isCountryOfOriginRequired": False,
            "isDealPositionQuotationAndQuantityOfferingEnabled": False,
            "parentTradeId": None,
            "parentTradeNumber": None,
            "isSpecificSupplier": False,
            "specificSupplierSubtype": 0,
            "isSpecificSupplierTradeCanBeCreated": False,
            "specificSupplierTradeCreationErrors": None,
            "qualifiedSuppliers": [],
            "isInitialMaximumContractPriceTrade": False,
            "imcpCreatingLimit": None
        },
        "warnings": [],
        "isImproveApplication": False
    }


