search_model = {
            "page": 1,
            "size": 10,
            "isReviewAwaiting": False,
            "isCustomerSendingAwaiting": False,
            "isCustomerSigningAwaiting": False,
            "isSupplierSigningAwaiting": False,
            "isSupplierAdditionalAgreementSignAwaiting": False,
            "isDealTerminationSignAwaiting": False,
            "isChangeDealTermsProtocolReceived": False,
            "isWinner": False,
            "isLoser": False,
            "searchText": "100202879124100050",  # "Оказание услуг по реализации арестованного имущества -оценка -оценки -оценке -оценкой -хранение -хранении -хранения -хранением"
            "purchaseName": "",
            "number": None,
            "lotItemEatCodes": [],
            "productCode": None,
            "okpd2Codes": [],
            "ktruCodes": [],
            "purchaseTypeIds": [],
            "types": [],
            "customerId": None,
            "customerInn": None,
            "customerKpp": None,
            "supplierNameOrInn": None,
            "purchaseMethods": [],
            "priceStart": None,
            "priceEnd": None,
            "deliveryAddressRegionCodes": [],
            "deliveryAddress": None,
            "contractPriceStart": None,
            "contractPriceEnd": None,
            "applicationFillingStartDate": None,
            "applicationFillingEndDate": None,
            "contractSignDateStart": None,
            "contractSignDateEnd": None,
            "deliveryDateStart": None,
            "deliveryDateEnd": None,
            "isSmpOnly": False,
            "isEatOnly": True,
            "stateDefenseOrderOnly": None,
            "createDateTime": None,
            "excludeCancelledByCustomer": False,
            "excludeExternalTrades": False,
            "publishDateBegin": None,
            "publishDateEnd": None,
            "updateDateBegin": None,
            "updateDateEnd": None,
            "applicationFillingStartDateBegin": None,
            "applicationFillingStartDateEnd": None,
            "customerContractNumber": None,
            "hasLinkedExternalTrade": None,
            "eisTradeNumber": None,
            "isSpecificSupplier": False,
            "isRussianItemsPurchase": None,
            "organizerRegion": None,
            "organizerRegions": [],
            "etpType": None,
            "favoriteTag": None,
            "lotStates": [2],  # [2] - новые, [] - все
            "sort": [
                {
                    "fieldName": "publishDate",
                    "direction": 2
                }
            ]
        }
